### PR TITLE
some typos in atlas-scripts

### PR DESCRIPTION
**Pull request by fchapoton**
partial care for typos in atlas-script

### CODE REVIEW

**Comment by davidvogan** [comment]
Dear Frédéric,

Thank you for this work! We will discuss merging the patches at our next
group meeting.

Yours,
David

**Comment by davidvogan** [comment]
Dear Frederic,

Thank you for this work! We will discuss merging the patches at our next group meeting.

Yours,
David

**Comment by fchapoton** [comment]
so, did you meet yesterday ? My changes are rather innocuous and should be easy to merge.

**Comment by davidvogan** [comment]
Dear Frédéric,

Thank you again for this work! We did decide in September to merge the
corrections you suggested at that time; but apparently we never did that. I
have now merged the three original pull requests, and this one as well.

Yours,
David

**Pull request merged**
