### PR TITLE
trying to add a codespell linter

### PR DESCRIPTION
**Pull request by fchapoton**
just an experiment, to see if this is doable

### CODE REVIEW

**Comment by fchapoton** [comment]
alas, the linter is not run by github. Maybe one way out would be to activate it first on a single file where codespell reports no error, and then extend it later to the whole directories.

**Comment by fchapoton** [comment]
any comment on the idea ?

**Comment by jeffreyadams** [comment]
This looks interesting but I need a little more information. Does the linter run automatically? Is it integrated into github in some way? Or is it just a tool that we can run on our own?

Jeff Adams

**Comment by fchapoton** [comment]
> This looks interesting but I need a little more information.

You may want to look at recents pull requests in Macaulay2, now using the same "linter" among other checks

for instance https://github.com/Macaulay2/M2/pull/2699 in the section "Checks"

> Does the linter run automatically?

yes, in principle, it will run once on every new pull request, and should report on the web page of the pull request. The report will say on which line of which files there are possibly spelling errors. 

I am not yet mastering the process and do not understand why it has not run yet here. Maybe it needs to be integrated in the main branch before it is triggered, but I am not sure.

> Is it integrated into github in some way? Or is it just a tool that we can run on our own?

This is run by github on some github machines. This is less interesting if the development process does not go through merge requests on github.

**Comment by fchapoton** [comment]
Maybe you need to "activate the Github Actions" on the repository, if not yet done ?

**Comment by davidvogan** [comment]
Dear Frederic,

There are some complications with implementing the changes you have made.
Development work on the software happens mostly on the branch "latest," and
occasionally in some other branches. Changes in those branches are
eventually merged to "master." When the branch master has separate changes
(like the corrections you have found), the merge  becomes a bit more
complicated. When you have corrected spelling errors in comments in the
.cpp and .h files, then "make" thinks that the code in those files has
changed, and so wants to recompile the software.

I'm sure that there are reasonable ways to deal with these issues, but we
have not addressed them yet. That's why we have not activated these changes.

Yours,
David

**Comment by fchapoton** [comment]
ok, thanks. I understand. What about my other pull request, just fixing a bunch of typos ?

**Pull request closed without merging**
